### ISSUE TITLE
Week 0 --- Python, LaTeX and Git (introduction and task assignment)

### ISSUE THREAD

**Issue by pppppass** [pppppass/ToolsSeminar#2]
Is that ok to organize a seminar at 20:40 on Nov. 30 at 1570 (No. 1 Science Building)? Main topics will be designing and assigning tasks, and introduce some basic usage of Python, LaTeX, git / GitHub and so on.

(1) Is the time appropriate for everyone?
(2) Are there any more topics to be covered?
(3) Any suggestions and questions?

**POST COMMENT HERE, EVEN SIMPLY "OK"**

**Comment by caitianle1998** [comment]
Fu

**Comment by zzttzz** [comment]
Sure

**Comment by zdhNarsil** [comment]
周四有可以推掉的不重要的事……

**Comment by YiifeiWang** [comment]
Ojbk

**Comment by 2prime** [comment]
Will the speaker give us a simple introduction to the Juptyer Notebook? I think it will be a convenient way for us to give demonstration.

**Comment by Jason-jzy** [comment]
I THINK IT'S OK~

**Comment by JikaiHou** [comment]
OK

**Comment by RoyWangyx** [comment]
OK~

**Comment by pppppass** [comment]
Yes, Jupyter Notebook together with IPython is of great use and I'll demonstrate it. A list of resources related will also be uploaded soon.

**Comment by 20171130** [comment]
Oh, my football  training is on every Thursday night, I am afraid it may not be possible for me to attend thw seminar
